name: nutrition_app_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.2.6

  path_provider: ^0.4.1
  cloud_firestore: ^0.8.2
  firebase_core: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/flutter.png
    - assets/config.json
    - assets/testnutrients.json
    - assets/testrecipes.json
