name: nutrition_app_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.2.6

  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4
  firebase_performance: ^0.0.8
  firebase_database: ^1.0.5
  firebase_auth: ^0.6.6

  english_words: ^3.1.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
