name: nutrition_app_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.2.6

  path_provider: ^0.4.1
  cloud_firestore: ^0.8.2+3
  firebase_core: ^0.2.5
  firebase_auth: ^0.6.6
  shared_preferences: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
      weight: 400
    - asset: fonts/Montserrat-Italic.ttf
      weight: 400
      style: italic
    - asset: fonts/Montserrat-Medium.ttf
      weight: 500
    - asset: fonts/Montserrat-MediumItalic.ttf
      weight: 500
      style: italic
  - family: RobotoSlab
    fonts:
    - asset: fonts/RobotoSlab-Regular.ttf
      weight: 400
    - asset: fonts/RobotoSlab-Bold.ttf
      weight: 600
  assets:
  - assets/config.json
  - assets/testnutrients.json
  - assets/testrecipes.json
